# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readExtractionMetrics <- function(f) {
    .Call('InterOp_readExtractionMetrics', PACKAGE = 'InterOp', f)
}

readQualityMetrics <- function(f) {
    .Call('InterOp_readQualityMetrics', PACKAGE = 'InterOp', f)
}

readErrorMetrics <- function(f) {
    .Call('InterOp_readErrorMetrics', PACKAGE = 'InterOp', f)
}

readTileMetrics <- function(f) {
    .Call('InterOp_readTileMetrics', PACKAGE = 'InterOp', f)
}

readCorrectedIntMetrics <- function(f) {
    .Call('InterOp_readCorrectedIntMetrics', PACKAGE = 'InterOp', f)
}

readControlMetrics <- function(f) {
    .Call('InterOp_readControlMetrics', PACKAGE = 'InterOp', f)
}

readImageMetrics <- function(f) {
    .Call('InterOp_readImageMetrics', PACKAGE = 'InterOp', f)
}

