// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// readExtractionMetrics
Rcpp::DataFrame readExtractionMetrics(CharacterVector f);
RcppExport SEXP InterOp_readExtractionMetrics(SEXP fSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< CharacterVector >::type f(fSEXP );
        Rcpp::DataFrame __result = readExtractionMetrics(f);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// readQualityMetrics
Rcpp::List readQualityMetrics(CharacterVector f);
RcppExport SEXP InterOp_readQualityMetrics(SEXP fSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< CharacterVector >::type f(fSEXP );
        Rcpp::List __result = readQualityMetrics(f);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// readErrorMetrics
Rcpp::DataFrame readErrorMetrics(CharacterVector f);
RcppExport SEXP InterOp_readErrorMetrics(SEXP fSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< CharacterVector >::type f(fSEXP );
        Rcpp::DataFrame __result = readErrorMetrics(f);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// readTileMetrics
Rcpp::DataFrame readTileMetrics(CharacterVector f);
RcppExport SEXP InterOp_readTileMetrics(SEXP fSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< CharacterVector >::type f(fSEXP );
        Rcpp::DataFrame __result = readTileMetrics(f);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// readCorrectedIntMetrics
Rcpp::DataFrame readCorrectedIntMetrics(CharacterVector f);
RcppExport SEXP InterOp_readCorrectedIntMetrics(SEXP fSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< CharacterVector >::type f(fSEXP );
        Rcpp::DataFrame __result = readCorrectedIntMetrics(f);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// readControlMetrics
Rcpp::DataFrame readControlMetrics(CharacterVector f);
RcppExport SEXP InterOp_readControlMetrics(SEXP fSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< CharacterVector >::type f(fSEXP );
        Rcpp::DataFrame __result = readControlMetrics(f);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// readImageMetrics
Rcpp::DataFrame readImageMetrics(CharacterVector f);
RcppExport SEXP InterOp_readImageMetrics(SEXP fSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< CharacterVector >::type f(fSEXP );
        Rcpp::DataFrame __result = readImageMetrics(f);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
